config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "home" => "home#index"

  route :login do
    create as: "login", bare: true
    get :check_inbox
    get :verify_email
  end

  post "logout" => "login#destroy"
  get "u/:username" => "profile#show",
      as: :profile

  route :posts do
    create
    update
    show
  end

  post "posts/:post_id/like" => "likes#create", as: :like_post, format: false
  delete "posts/:post_id/like" => "likes#delete", format: false

  post "posts/:post_id/comments" => "comments#create",
       as: :post_comments,
       format: false
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_global_meta_data

  private def set_global_meta_data
    page_meta.tag :user_id, current_user&.id.to_s
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def svg_image_tag(name)
    content_tag :span, class: "svg-#{name}" do
      File.read(
        Rails.root.join("app/assets/images/#{name}.svg")
      ).html_safe # rubocop:disable Rails/OutputSafety
    end
  end

  def icon(name, **kwargs)
    content_tag :svg, class: "icon icon--#{name}", **kwargs do
      content_tag :use, nil, href: "#icon--#{name}"
    end
  end

  def post_location(post)
    [post.city, post.region, t(post.country, scope: "countries")].join(", ")
  end

  def gravatar(email, size: 50, **kwargs)
    email_digest = Digest::MD5.hexdigest(email.to_s)
    image_tag "https://gravatar.com/avatar/#{email_digest}?s=#{size * 2}",
              **kwargs,
              class: "avatar"
  end

  def page_id
    [controller.controller_name, controller.action_name].join("-")
  end

  def like_button(post)
    data = {
      controller: "like-button",
      action: "click->like-button#handleClick",
      liked: post.liked_by?(current_user),
      post_id: post.id
    }

    content_tag :button, type: "button", data: data do
      icon(:heart_outline) + icon(:heart)
    end
  end
end

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <p class="flash-message <%= type %>">
    <%= message %>
  </p>
<% end %>

app/views/application/_head.html.erb
<head>
  <%= page_meta %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

app/views/application/_main_header.html.erb
<nav class="main-header absolute top-0 right-0 p-2 flex">
  <% if user_logged_in? %>
    <div data-controller="menu" class="flex flex-row items-center ml-auto">
      <%= link_to t(".explore"), home_path, class: "text-base mr-4 no-underline text-inherit" %>

      <%= link_to new_post_path, class: "text-base mr-4 no-underline text-inherit" do %>
        <%= icon(:plus_square) %>
        <%= t(".add_post") %>
      <% end %>

      <button type="button" data-menu-target="button" data-action="click->menu#handleClick">
        <%= gravatar current_user.email,
                     alt: t(".user_photo_alt", username: current_user.username) %>
      </button>

      <ul class="menu" hidden data-menu-target="menu">
        <li class="menu-item">
          <%= link_to home_path, class: "menu-action" do %>
            <%= icon :gear %>
            <%= t(".settings") %>
          <% end %>

        </li>
        <li class="menu-item">
          <%= link_to home_path, class: "menu-action" do %>
            <%= icon :bubble_exclamation %>
            <%= t(".send_feedback") %>
          <% end %>

        </li>
        <li class="menu-item with-separator">
          <%= button_to logout_path, class: "menu-action" do %>
            <%= icon :close %>
            <%= t(".logout") %>
          <% end %>

        </li>
      </ul>
    </div>
  <% else %>
    <ul class="main-nav">
      <li>
        <%= link_to t(".home"), home_path %>
      </li>

      <li class="ml-4">
        <%= link_to t(".explore"), home_path %>
      </li>

      <li class="ml-4">
        <%= link_to t(".join_photomatic"),
            login_path,
            class: "text-accent" %>
      </li>
    </ul>
  <% end %>
</nav>

app/views/application/_menu.html.erb
<nav class="absolute top-0 right-0 m-2">
  <% if user_logged_in? %>
    <div data-controller="menu" class="flex flex-row items-center">
      <%= link_to t(".explore"), home_path, class: "text-sm mr-4" %>

      <%= link_to new_post_path, class: "text-sm mr-4" do %>
        <%= icon(:plus_square) %>
        <%= t(".add_post") %>
      <% end %>

      <button type="button" data-menu-target="button" data-action="click->menu#handleClick">
        <%= gravatar current_user.email,
                     alt: t(".user_photo_alt", username: current_user.username) %>
      </button>

      <ul class="menu" hidden data-menu-target="menu">
        <li class="menu-item">
          <%= link_to home_path, class: "menu-action" do %>
            <%= icon :gear %>
            <%= t(".settings") %>
          <% end %>

        </li>
        <li class="menu-item">
          <%= link_to home_path, class: "menu-action" do %>
            <%= icon :bubble_exclamation %>
            <%= t(".send_feedback") %>
          <% end %>

        </li>
        <li class="menu-item with-separator">
          <%= button_to logout_path, class: "menu-action" do %>
            <%= icon :close %>
            <%= t("actions.logout") %>
          <% end %>

        </li>
      </ul>
    </div>
  <% else %>
    <ul class="flex flex-row text-xs uppercase font-bold text-slate-500 p-3">
      <li>
        <%= link_to t(".home"), home_path %>
      </li>

      <li class="ml-4">
        <%= link_to t(".explore"), home_path %>
      </li>

      <li class="ml-4">
        <%= link_to t(".join_photomatic"),
            login_path,
            class: "text-accent" %>
      </li>
    </ul>
  <% end %>
</nav>

app/views/application/_top_bar.html.erb
<div class="topbar">
  <%= link_to home_path do %>
    <%= svg_image_tag "logo" %>
  <% end %>
</div>

app/views/application/_user_info.html.erb
<div class="user-info <%= local_assigns[:class] %>">
  <%= gravatar user.email %>

  <div class="user-info--name-group">
    <span class="user-info--name"><%= user.display_name %></span>
    <%= link_to user.username,
                profile_path(user),
                class: "user-info--username" %>
  </div>
</div>